sudo: required

services:
    - docker

before_install:
    - docker build -t wakeupcolumn/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true wakeupcolumn/react-test npm test

after_success:
    - docker build -t wakeupcolumn/multi-client ./client
    - docker build -t wakeupcolumn/multi-nginx ./nginx
    - docker build -t wakeupcolumn/multi-server ./server
    - docker build -t wakeupcolumn/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push wakeupcolumn/multi-client
    - docker push wakeupcolumn/multi-nginx
    - docker push wakeupcolumn/multi-server
    - docker push wakeupcolumn/multi-worker 
    


